name: Blazor wasm github pages

on:
  push:
    branches:
      - feature/blazor-wasm
  # pull_request:
  #   branches:
  #     - main
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - uses: actions/checkout@v2

      # Install .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x
          
      # Install dotnet wasm buildtools workload
      - name: Install .NET WASM Build Tools
        run: dotnet workload install wasm-tools
          
      # Publishes Blazor project to the release-folder
      - name: Publish .NET Core Project
        run: |
          dotnet publish src/HomeDarts/HomeDarts.csproj -c:Release -p:GHPages=true -o dist/Web --nologo
          ls dist/Web
          ls dist/Web/wwwroot

      - name: Set base path to home-darts
        run: sed 's/base href="\/"/base href="\/home-darts\/"/' dist/Web/wwwroot/index.html

      - name: Commit wwwroot to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          BRANCH: gh-pages
          FOLDER: dist/Web/wwwroot
